# --- Figure out the caller's current public IP, so SSH can be locked to it
#     by default instead of opening port 22 to the whole internet. ---
data "http" "my_ip" {
  url = "https://checkip.amazonaws.com"
}

locals {
  app_dir            = "/home/ec2-user/${var.project_name}"
  detected_cidr      = "${chomp(data.http.my_ip.response_body)}/32"
  effective_ssh_cidr = coalesce(var.allowed_ssh_cidr, local.detected_cidr)
  # Latest Amazon Linux 2023 AMI, matching whatever architecture the chosen
  # instance type needs (x86_64 for t3/t2, arm64 for t4g).
  is_arm = strcontains(var.instance_type, "g.")
}

data "aws_ami" "amazon_linux" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-${local.is_arm ? "arm64" : "x86_64"}"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# --- A dedicated key pair for this project, generated by Terraform so
#     there's no manual "create a key pair in the console" step. ---
resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = "${var.project_name}-key"
  public_key = tls_private_key.this.public_key_openssh
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.this.private_key_pem
  filename        = "${path.module}/${var.project_name}-key.pem"
  file_permission = "0400"
}

# --- Security group: SSH from your current IP only, the app port from
#     anywhere (that's the whole point — players/organizers reach it from
#     wherever they are), all outbound traffic allowed. ---
resource "aws_security_group" "this" {
  name        = "${var.project_name}-sg"
  description = "SSH from the deployer's IP; app port from anywhere"

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [local.effective_ssh_cidr]
  }

  ingress {
    description = "App"
    from_port   = var.app_port
    to_port     = var.app_port
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "${var.project_name}-sg" }
}

resource "aws_instance" "this" {
  ami                    = data.aws_ami.amazon_linux.id
  instance_type          = var.instance_type
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [aws_security_group.this.id]

  root_block_device {
    volume_size = var.root_volume_gb
    volume_type = "gp3"
  }

  # Deliberately no Elastic IP — see deploy/README.md's cost note. The
  # auto-assigned public IP costs nothing while the instance is stopped.
  associate_public_ip_address = true

  user_data = templatefile("${path.module}/templates/user_data.sh.tpl", {
    project_name = var.project_name
    app_dir      = local.app_dir
    app_port     = var.app_port
  })
  user_data_replace_on_change = true

  tags = { Name = var.project_name }
}
